name: Golang Docker Build

on: push

env:
  CONTAINER_REPOSITORY: quay.io/alexandercalle
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: alexandercalle+almworkshop
          password: VNVUGRKQ3B9HMXTTV2JHMJ9Y2PTQPVZA74OL5XPUIGH4QOXX6N19KM97SV7KRFU3

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: quay.io/alexandercalle/alm-workshop

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
